### ISSUE TITLE
Upgrade ovh dependency to support python 3.10

### ISSUE THREAD

**Issue by istr** [octodns/octodns-ovh#2]
There is already a PR against ovh that addresses this issue: https://github.com/ovh/python-ovh/pull/108
Hopefully, the maintainers will accept this PR and publish 0.6.0 based on that.
I don't think there's any point in making any effort here other than to support the PR mentioned above.

**Comment by ross** [comment]
Looks like https://github.com/ovh/python-ovh/pull/108 has merged so this can happen. Will look into it later today.

**Comment by istr** [comment]
See https://github.com/octodns/octodns-ovh/pull/11
